language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
env:
  global:
    secure: kGrQL5m66v2kI1U3malS283/lX8xmf5ohh4pnLZcDttzRiNmVEoC0dKFhOHH1YeCQK8dmimjq+2rzs7eNkjuJ07ePzgLkUCjRT8b6xaM6q8cO8eZc/CHLl5JTOvh2sWX74Dvvvvp08l5GwC/g/SapoKm0QerDBWts9IsJb8ZrSYcPaEElWQWZLAK+QHgeAQnIoVJTjWxGi101D1jrS/BA6tmcwq/JLC5d09XWFPhusD4Jk74/8U8wBkdq15jZNW2NHzv9Wm8zDCQOJMWy8mvrdmYvUG7/4VntMiROB4gO8nMn9BnDHizY8CLsp6Qzi9IjgYamgInleONdU8Xi/QwkClAZOZFu0qUIihRU028YT6SgKCVb6cVwwhXkgof1UDeZFUxaMQo7HsEGZl+6fr+/mjFcOc5el/c6bZifOzRbKL1XI989BL8IyFSV1ejTJugjjGwUXfSn1aRO1dAPGHuwv6xKqUlZgsNIBf6uPc0N5dlNQ/lfzlpq9O825UXBgnMD7NoVLYbmpCagy+vakN+Mz/VIWEVnEYgLIOq3ZOrgIQM4eH0DJey2d3E9DyiEdX+gGN4OixzuTkD5ddROXQpRfyZeObA8UBLB1BRfvgEFaNC/9wZH5OvBfFQr4Iu/llM682p1DATd4cK13hgZXecgq4MmcTHWfvClHc0TlIVX60=
